name: Build and Deploy

on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: felixab08/app-monografia # Asegúrate de que el nombre del repositorio sea correcto
          path: app-monografia # Clonar el repositorio en un subdirectorio específico

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install packages
        run: npm ci

      - name: Bundle
        run: npm run build:prod

      - name: Test
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: develop
          folder: dist/browser
          token: ${{ secrets.GH_TOKEN }}
