name: Build and Deploy

on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List files for debugging
        run: ls -la

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install packages
        run: npm i

      - name: Test
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Bundle
        run: npm run build:prod

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Despliega a la rama gh-pages
          folder: dist/browser # Ajusta esta ruta si es necesario
          token: ${{ secrets.GH_TOKEN }} # Usar el token integrado
